services:
  documents-api:
    container_name: documents-api
    image: documents-api
    build:
      context: .
      dockerfile: SWKOM/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    develop:
      watch:
        - action: rebuild
          path: .