services:

  documents-api:
    container_name: documents-api
    image: documents-api_image
    build:
      context: .
      dockerfile: SWKOM/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081 # Stellt sicher, dass nur HTTP verwendet wird
    depends_on:
        - rabbitmq
        - DocumentDAL
    develop:
      watch:
        - action: rebuild
          path: .

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports: 
        - "5672:5672"
        - "15672:15672"
    volumes:
        - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  webui:
    container_name: webui
    image: webui_image
    build:
      context: ./WebUI
      dockerfile: Dockerfile
    ports:
     - "80:80"
    volumes:
      - ./WebUI/nginx.conf:/etc/nginx/nginx.conf  # Binde die Nginx-Konfigurationsdatei ein
      - ./WebUI/wwwroot:/app/wwwroot  # Statische Dateien mounten
    depends_on:
      - documents-api
    develop:
      watch:
        - action: rebuild
          path: .

  DocumentDAL:
    container_name: DocumentDAL
    image: documentdal_image
    build:
      context: .
      dockerfile: DocumentDAL/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8082
    depends_on:
      # - documents-api
      - postgres
    develop:
      watch:
        - action: rebuild
          path: .

  ocr_worker:
    container_name: ocr_worker
    image: ocr_worker_image
    build:
      context: ./OcrWorker  
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./uploads:/app/uploads

  postgres:
    container_name: postgres_container
    image: postgis/postgis:17-3.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-DocManagerDB}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.12
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped


networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: