services:
  documents_api:
    container_name: documents_api
    image: documents_api_image
    build:
      context: .
      dockerfile: SWKOM/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081 # Stellt sicher, dass nur HTTP verwendet wird
    depends_on:
        - rabbitmq
        - document_dal
    develop:
      watch:
        - action: rebuild
          path: .
    volumes:
        - ./uploads:/app/uploads
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports: 
        - "5672:5672"
        - "15672:15672"
    volumes:
        - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - app-network

  webui:
    container_name: webui
    image: webui_image
    build:
      context: ./WebUI
      dockerfile: Dockerfile
    ports:
     - "80:80"
    volumes:
      - ./WebUI/nginx.conf:/etc/nginx/nginx.conf  # Binde die Nginx-Konfigurationsdatei ein
      - ./WebUI/wwwroot:/app/wwwroot  # Statische Dateien mounten
    depends_on:
      - documents_api
    develop:
      watch:
        - action: rebuild
          path: .
    networks:
      - app-network

  document_dal:
    container_name: document_dal
    image: documentdal_image
    build:
      context: .
      dockerfile: DocumentDAL/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8082
    depends_on:
      - postgres
    develop:
      watch:
        - action: rebuild
          path: .
    networks:
      - app-network

  ocr_worker:
    container_name: ocr_worker
    image: ocr_worker_image
    build:
      context: ./OcrWorker
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network

  indexing_worker:
    container_name: indexing_worker
    image: indexing_worker_image
    build:
      context: ./ElasticSearch
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - elasticsearch
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgis/postgis:17-3.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-DocManagerDB}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
      - app-network
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.12
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
      - app-network
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/data
    networks:
      - elastic
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - elastic
      - app-network

networks:
  postgres:
    driver: bridge
  elastic:
    driver: bridge
  app-network:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    elasticsearch-data:
    minio-data:
    

