#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM nginx:alpine
COPY wwwroot /usr/share/nginx/html
EXPOSE 80